In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [4]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
  #data = data.drop(data.columns[[2]], axis = 1)

In [6]:
 #data.head()
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [8]:
#data['log_x'] = np.log(data['x'])
#data['log_y'] = np.log(data['y'])

In [10]:
  #x = data['SAT']   # dependent variable
   #y = data['GPA']   # Independent variable
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [12]:
#x.shape

In [14]:
#y.shape

In [16]:
# 2-D array
#x_matrix = x.values.reshape(-1,1)
#x_matrix.shape

In [18]:
# make object of the class
reg = LinearRegression()

In [20]:
reg.fit(x, y)

LinearRegression()

# R-Square

In [23]:
#reg.score(x_matrix, y)

# Coefficient

In [26]:
reg.coef_

array([ 0.00165354, -0.00826982])

# Intercept

In [29]:
reg.intercept_

0.29603261264909486

In [31]:
 #new_data = pd.DataFrame(data[1740, 1760], columns = ['SAT'])
  #new_data

# Making Prediction

# Multi- LR R_Square

In [35]:
reg.score(x,y)

0.4066811952814282

# Formula for Adjusted R^2 ((adj)R^2)
 $R^2_{adj .} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [38]:
adj_r_sq = 1 - (1 - reg.score(x,y)) * ((x.shape[0] - 1)/(x.shape[0] - x.shape[1] - 1)) 

In [40]:
print(adj_r_sq)

0.39203134825134


In [42]:
 from sklearn.feature_selection import f_regression

In [44]:
f_regression(x,y)  # featured values   and  p-values  

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [46]:
p_values = f_regression(x,y)[1]

In [48]:
p_values

array([7.19951844e-11, 6.76291372e-01])

In [51]:
p_values.round(3)

array([0.   , 0.676])

# CREATING SUMMARY TABLE WITH P-VALUES

In [54]:
res_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])
res_summary['Coeffient'] = reg.coef_
res_summary['P_values'] = p_values.round(3)

In [56]:
res_summary

Features  Coeffient  P_values
0         SAT   0.001654     0.000
1  Rand 1,2,3  -0.008270     0.676